# Run a Gyges Game and Encode it

In [7]:
import numpy as np
import sys

sys.path.append("../")
from src.players import Player
from src.game_engine import GygesGame


SEED = 532
rng = np.random.default_rng(seed=SEED)

In [8]:

starting_config = [2,1,3,3,1,2]
    
random_config = [2, 1, 3, 3, 1, 2]
rng.shuffle(random_config)

pw = Player("W", soul='random', seed=SEED, verbose=True)
w_starting_config = random_config
pb = Player("B", soul='human', verbose=True)
b_starting_config = starting_config

game = GygesGame(w_starting_config, b_starting_config)
game.add_players(pb, pw)


Added player: B to the game.
Added player: W to the game.


In [9]:
game.start()
game.play_game(max_turns=1000, verbose=True)

Starting a new game of Gyges!

Initial configuration:
W|  -   -   -   -   -   -  |
1|  2   3   1   1   2   3  |
2|  0   0   0   0   0   0  |
3|  0   0   0   0   0   0  |
4|  0   0   0   0   0   0  |
5|  0   0   0   0   0   0  |
6|  2   1   3   3   1   2  |
B|  -   -   -   -   -   -  |
    0   1   2   3   4   5  
Player W turn.

W: select cell (1, 4) with value 2.
  strategy: [[2, 2]]
W|  -   -   -   -   -   -  |
1|  2   3   1   1   x   3  |
2|  0   0   0   0   x   0  |
3|  0   0   0   0   2   0  |
4|  0   0   0   0   0   0  |
5|  0   0   0   0   0   0  |
6|  2   1   3   3   1   2  |
B|  -   -   -   -   -   -  |
    0   1   2   3   4   5  
Player B turn.

B: select cell (-2, 2) with value 3.
 you jumped on piece with value 3, continue...
  strategy: [[1, 4, 2], [1, 1, 1]]
W|  -   -   -   -   -   -  |
1|  2   3   1   1   0   3  |
2|  0   0   0   0   0   0  |
3|  0   0   0   3   2   0  |
4|  0   0   0   x   0   0  |
5|  0   0   x   x   0   0  |
6|  2   1   x  3x   1   2  |
B|  -   -   -  

In [11]:
game.game_data[1]

[(-2, 2),
 [1, 4, 2, 1, 1, 1],
 [[0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [0.08333333333333333,
   0.125,
   0.041666666666666664,
   0.041666666666666664,
   0.0,
   0.125],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [0.0, 0.0, 0.0, 0.125, 0.08333333333333333, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
  [0.08333333333333333,
   0.041666666666666664,
   0.0,
   0.125,
   0.041666666666666664,
   0.08333333333333333],
  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]]

## Encoding the Game

In [85]:
timestep = 2
game_step = game.game_data[timestep]

active_player = timestep % 2
print(f'Player {active_player}')
players_channels = np.array(
    [np.zeros((8,6)), np.zeros((8,6))]
)
players_channels[active_player] = np.ones((8, 6))
# print(f'Player Channels:\n{players_channels}')

home_row = np.zeros((8, 6))
home_row[active_player - 1, :] = 1.
# print(f'Home Row:\n{home_row}')

reverse_index = (1 - active_player) * 2 - 1
valid_starting_row = np.argmax(np.any(game_step[-1][::reverse_index], axis=1))
valid_starting_pos = np.zeros((8, 6))
valid_starting_pos[valid_starting_row, :] = 1.
valid_starting_pos = valid_starting_pos[::reverse_index]
print(f'Valid starting positions:\n{valid_starting_pos}')

Player 0
Valid starting positions:
[[0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [86]:
np.array(game_step[-1]) * valid_starting_pos

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.125     , 0.04166667, 0.04166667, 0.        ,
        0.125     ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        ]])

Valid starting positions:
[[0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
